### ISSUE TITLE
Show images in-line

### ISSUE THREAD

**Issue by sfsheath** [kenchreai/kaa-data-entry#9]
For kaaont:photograph and  kaaont:drawing properties show the PNG file as well as relative path to file.

**Comment by BlaiseGratton** [comment]
@sfsheath: I have image tags up but I must be missing something about pointing the image URLs at the right location. E.g., `http://kenchreai.org/kaa/photography/threpsiades/inventoried-objects/kth0008.png` comes up blank

**Comment by sfsheath** [comment]
Prepend "http://kenchreai-archaeological-archive-files.s3-website-us-west-2.amazonaws.com/" to all kaaont:photograph, kaaont:drawing values. As well as to kaaont:file values that end in .jpg or .png . That last is a remnant but I haven't updated all kaaont:file properties to be either drawings or photographs.

**Comment by BlaiseGratton** [comment]
Okay... so does there need to be a mapping from a resource such as `photographs/kth/kth0008` on kaa to `photography/threpsiades/inventoried-objects/kth0008.png`? Easy to do. Or are we expecting the users to enter a string such as `photography/threpsiades/inventoried-objects/kth0008.png` directly?

**Comment by BlaiseGratton** [comment]
Also, how big do you want these to be, essentially thumbnails in the table?

**Comment by sfsheath** [comment]
No mapping necessary. We only need to take the property value and prepend the AWS host name. Many now imply a directory structure (e.g, https://kenchreai-data-editor.herokuapp.com/#/detail/ke/ke0024). But since we've moved to S3 buckets, that's an illusion left over from when these files were in a linux directory. See https://kenchreai-data-editor.herokuapp.com/#/detail/kth/kth0007 for just the bare file name. Same code generates link to image by a simple prepend. See source of http://kenchreai.org/kaa. (If you look at that, you'll see there are thumbnail versions. But I'm going to move thumbs into a separate S3 bucket so we can ignore that for now...)

 I think we want to keep the exact same editing interface. But just add a ~300px wide img element that displays the image directly from S3 when one is available. For now, I'm the only one adding images. Perhaps we can make a fancier image upload capability but that's currently overkill.

 Does this seem workable? Meant to be a trivial and robust structure.

**Comment by BlaiseGratton** [comment]
The file name from kth0007 makes perfect sense because of the S3 flat bucket structure. That was all I needed - should get this deployed sometime today.

**Comment by BlaiseGratton** [comment]
Okay... had some package issues with the deployment, but preliminary inline images are up there. Since I was basing the functionality off of looking at kth0007 & kth0008, I'm don't feel like I should close this issue unless it seems to you that it's working in all cases.

**Comment by sfsheath** [comment]
Works well. Thx!
